const CONFIG = {
    introTitle: 'Em yêu à!',
    introDesc: `Giận thì giận mà thương thì thương đúng hông nà`,
    btnIntro: 'hihi',
    title: 'Em tui còn có giận hông đấy ta',
    desc: 'Huhu',
    btnYes: 'Mình xin lỗi, mình xin lỗi được chưa :v',
    btnNo: 'Em đùa tui. Hứ',
    question:'Yêu hông, yêu hay không yêu nói một lời thôi 😂😂😂',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Nhớ em quá.  Chụp hình gửi anh đi',
    btnAccept: '<3',
    messLink:'https://www.facebook.com/messages/t/100010009530926}'
